apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: {{ include "mediawiki-chart.fullname" . }}
spec:
  ports:
    - port: 3306
  selector:
    app: mysql
  clusterIP: None 
---
apiVersion: v1
kind: Service
metadata:
  name: mediawiki
  labels:
    app: {{ include "mediawiki-chart.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: mediawiki

